# -*- coding: utf-8 -*-
"""project 2.o

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zbc4zfKzyiQTiew5r0vRY974DE5Mfu-0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve

np.random.seed(42)

n = 300

data = pd.DataFrame({
    "age": np.random.randint(18, 60, n),
    "salary": np.random.randint(20000, 100000, n),
    "balance": np.random.randint(0, 200000, n)
})

data["churn"] = (
    (data["balance"] > 100000).astype(int) |
    (data["salary"] < 40000).astype(int)
).astype(int)

data.head()

from pandas.core.api import RangeIndex

print(data.shape)

print(data.info())

print(data.describe())

print(data['churn'].value_counts())

features = ["age", "salary", "balance"]

for col in features:
    plt.figure()
    plt.scatter(data[col], data["churn"])
    plt.xlabel(col)
    plt.ylabel("churn")
    plt.show()

x = data[["age", "salary", "balance"]]
y = data["churn"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

coeff_df = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model.coef_[0]
})

print(coeff_df)

new_data = pd.DataFrame({
    "age": [35],
    "salary": [30000],
    "balance": [150000]
})

print("Churn prediction", model.predict(new_data)[0])
print("Probability:", model.predict_proba(new_data)[0][1])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

np.random.seed(42)

data = pd.DataFrame({
    "hours_studied": np.random.randint(1, 10, 50),
    "attendance": np.random.randint(50, 100, 50),
})

x = data[["hours_studied", "attendance"]]

model = KMeans(n_clusters=3, random_state=42, n_init=10)
data["cluster"] = model.fit_predict(x)

print(data.head())

score = silhouette_score(x, data["cluster"])
print("Silhouette Score:", score)

plt.scatter(data["hours_studied"], data["attendance"], c=data["cluster"])

centers = model.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], marker='x', s=200)

plt.xlabel("Hours Studied")
plt.ylabel("Attendance")
plt.title("Student Segmentation")
plt.show()

new_student = [[6,80]]

predicted_cluster = model.predict(new_student)

print("New student belongs to cluster:", predicted_cluster[0])

data.groupby("cluster").mean()